[project]
site_name = "Plant Controller"
repo_url = "https://github.com/DisasterlyDisco/plant-controller"
docs_dir = "docs"
site_dir = "site"
nav = [
  {"Home" = "index.md"},
  {"Quick Start Quide" = [
    "pt/controller_3/setup/quick_start.md",
  ]},
  {"Custom Setups" = "pt/controller_3/setup/custom_setups.md"},
  {"Documentation" = [
    "pt/controller_3/documentation/index.md",
    {"Software" = [
      "pt/controller_3/documentation/software/index.md",
      {"plant_controller" = [
        "pt/controller_3/documentation/software/plant_controller/index.md",
        {"Command Line Interface" = "pt/controller_3/documentation/software/plant_controller/cli.md"},
        {"Source Code" = [
          "api/plant_controller/index.md",
          "api/plant_controller/cli_helpers.md",
          "api/plant_controller/com_bus.md",
          "api/plant_controller/database.md",
          "api/plant_controller/datapoint.md",
          "api/plant_controller/greenhouse.md",
          "api/plant_controller/plant.md",
          {"pump_schedules" = [
            "api/plant_controller/pump_schedules/index.md",
            "api/plant_controller/pump_schedules/daily.md",
          ]},
          {"pumps" = [
            "api/plant_controller/pumps/index.md",
            "api/plant_controller/pumps/ad20p_1230e.md",
          ]},
          {"sensors" = [
            "api/plant_controller/sensors/index.md",
            "api/plant_controller/sensors/as7341.md",
            "api/plant_controller/sensors/df_robot_temp_moist_ec.md",
            "api/plant_controller/sensors/sht45.md",
            "api/plant_controller/sensors/stemma.md",
          ]},
          "api/plant_controller/setup_actions.md",
          "api/plant_controller/unit.md",
          "api/plant_controller/web_api.md",
        ]},
      ]},
      {"Web API" = "pt/controller_3/software/web_api/index.md"},
    ]},
  ]},
  {"Previous Versions" = [
    "previous_versions.md",
    {"Controller 1" = [
      {"Parts" = "pt/controller_1/PARTS.md"},
      {"Assembly" = "pt/controller_1/assembly/ASSEMBLE.md"},
      {"References" = "pt/controller_1/REFERENCES.md"},
    ]},
    {"Controller 2" = [
      {"Parts" = "pt/controller_2/PARTS.md"},
    ]},
  ]},
]

[project.theme]
features = [
  "navigation.tabs",
  "navigation.top",
  "navigation.indexes",
  "content.code.copy",
]

[project.plugins.mkdocstrings.handlers.python]
paths = ["pt/controller_3/src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
allow_inspection = false
members_order = "source"
show_source = true

[project.plugins.mkdocstrings.handlers.python.options.docstring_options]
warnings = false
